# ckpt/config options(static)
# blip_path: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large.pth
blip_path: /home/jiaxin/Composed_BLIP/checkpoint/model_large.pth
med_config: /home/jiaxin/Composed_BLIP/checkpoint/med_config.json

# ckpt/logger options(dynamic)
checkpoint_base: checkpoint
visual_base: visualization
log_base: log

# dataset
data_base: dataset
image_base: images
pair_store_base: pair_store_clip

# loss_function:
quality_weight: 0.3
align_weight: 0.7

# model parameters
BLIP:
  # size of vit model; base or large
  vit: 'large'
  image_size: 224

Composed_BLIP:
  align_socre_evaluator_dim: 768
  qualify_evaluator_dim: 201728
